### ISSUE TITLE
cannot find module 'dockerode-ts' index.js missing from npm package?

### ISSUE THREAD

**Issue by philjones88** [Seikho/dockerode-ts#5]
As per title, with you kindly deploying the 2 new versions today I suddenly hit:

```module.js:474
    throw err;
    ^

Error: Cannot find module 'dockerode-ts'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.Module._load (module.js:420:25)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/phil/Documents/Projects/vq-protractor-setup/tmp/tasks/docker.js:2:22)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)```

I think rolling back to `0.2.12` and comparing it to `0.3.1` I can see index.js is missing?

**Comment by Seikho** [comment]
Derp. Sorry about that. Republished `v0.3.2` and added a prepublish script to prevent that happening again.
